### ISSUE TITLE
Menage addreses

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-vue-checkout#80] opened 2018-07-10 13:27 UTC
Problem: Logged users must fill up all fields as guest users at checkout even if they have some saved addresses and can choose it in standard checkout

Solution: Add functionality with a list of addresses in the first step. A User can choose from already saved addresses in order without fill everything once again. Also must remember about add possibility with fill up a custom address.

**Comment by szafran89** [comment] 2018-07-10 13:54
Duplicate of #68

**Closed as completed** 2018-07-10 13:54 UTC
Labels: duplicate
